global:
  slack_api_url: '{{slack_webhook_url}}'

route:
  receiver: 'slack'
  routes:
    - match:
        severity: critical
      receiver: pagerduty

receivers:
  - name: 'slack'
    slack_configs:
    - channel: '{{slack_channel}}'
      send_resolved: true
  - name: 'pagerduty'
    pagerduty_configs:
    - service_key: {{pagerduty_api_key}}